### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by luizbills** [gitpod-io/flutter_stock_example#1]
I created a gitpod instance, but the preview is empty (just a white screen) and not have errors on console.

**Comment by svenefftinge** [comment]
The flutter web app sometimes is a bit slow to come up but it does so reliably for me eventually.

**Comment by luizbills** [comment]
Nothing here yet...
These errors happen with you too?

![image](https://user-images.githubusercontent.com/1798830/68535014-62369a00-031a-11ea-8933-e401dccb31c2.png)

![image](https://user-images.githubusercontent.com/1798830/68535022-6f538900-031a-11ea-9273-c494939c07ed.png)

**Comment by geropl** [comment]
@luizbills I think this might be a problem with the [Dart developer service (dwds)](https://pub.dev/packages/dwds) where the frontend tries to connect to via SSE: https://pub.dev/packages/dwds
Once the SSE connection is dropped (by our proxy) the service gets unresponsive.
The exact cause and eventual fix is currently investigated.
@DanTup correct?

**Comment by DanTup** [comment]
How is the app being run here? I'm currently investigating an issue when using the Debug Extension where when the connection is dropped by the proxy after 60 seconds, the backend terminates (rather than waiting for a reconnect). The result looks a bit like this and I've started on a PR at https://github.com/dart-lang/sse/pull/19 to try and address this.

However, that work requires unreleased changes to Flutter and the Dart-Code plugin, which makes me think this is not being run in that way, and maybe is being run from the terminal?

If someone can give exact steps of what they're doing (or a repo I can just open in GitPod) I'm happy to take a look.
